20150527-19:58:24.274: Session FIX.4.4:LVSSG_ARB->LVARB schedule is daily, 00:01:00-UTC - 23:59:00-UTC
20150527-19:58:24.274: Created session: FIX.4.4:LVSSG_ARB->LVARB
20150527-19:58:25.090: Accepting session FIX.4.4:LVSSG_ARB->LVARB from /127.0.0.1:59401
20150527-19:58:25.091: Acceptor heartbeat set to 60 seconds
20150527-19:58:25.094: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20150527-19:58:25.109: Received logon
20150527-19:58:25.115: Responding to logon request
20150527-19:58:31.312: Disconnecting: Socket exception (/127.0.0.1:59401): java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
20150527-19:58:38.675: Accepting session FIX.4.4:LVSSG_ARB->LVARB from /127.0.0.1:59419
20150527-19:58:38.675: Acceptor heartbeat set to 60 seconds
20150527-19:58:38.675: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20150527-19:58:38.676: Received logon
20150527-19:58:38.677: Responding to logon request
20150527-20:14:36.100: Disconnecting: Socket exception (/127.0.0.1:59419): java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
20150527-20:14:45.090: Accepting session FIX.4.4:LVSSG_ARB->LVARB from /127.0.0.1:59692
20150527-20:14:45.090: Acceptor heartbeat set to 60 seconds
20150527-20:14:45.090: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20150527-20:14:45.090: Received logon
20150527-20:14:45.091: Responding to logon request
20150527-20:16:22.885: Disconnecting: Socket exception (/127.0.0.1:59692): java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
20150527-20:16:38.888: Accepting session FIX.4.4:LVSSG_ARB->LVARB from /127.0.0.1:59744
20150527-20:16:38.888: Acceptor heartbeat set to 60 seconds
20150527-20:16:38.888: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20150527-20:16:38.888: Received logon
20150527-20:16:38.889: Responding to logon request
20150527-20:46:55.167: Disconnecting: Socket exception (/127.0.0.1:59744): java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
